### ISSUE TITLE
projectile-ruby

### ISSUE THREAD

**Issue by JTOswayo** [rmm5t/dotfiles#6]
I believe that projectile-ruby is referenced somewhere, but yet not installed with your dot files repo.  When I try to launch emacs,  it fails with an undefined function referencing projectile-ruby

**Comment by rmm5t** [comment]
* The package.el packages should have auto-installed on the first emacs init (including projectile).
* Did you follow the installation instructions in the README?
* What version of emacs are you running? (I'm currently running `GNU Emacs 24.4.1`)

**Comment by JTOswayo** [comment]
This is what I am getting for an error 
I am using emacs_head from your install emacs head alias

![emacs](https://cloud.githubusercontent.com/assets/11273043/6762847/57e8a4ae-cf3e-11e4-8d21-a76d3a9f8079.jpg)

**Comment by JTOswayo** [comment]
Is projectile-rails a separate project?  I don't see it in the elope directory
![2015-03-20_20-21-52](https://cloud.githubusercontent.com/assets/11273043/6762867/d2cb8b1e-cf3e-11e4-8192-eab458e35b61.png)

**Comment by JTOswayo** [comment]
I think I found out what was happening -- It wasn't done compiling all of the apps from elpa,  and was trying to (add-hook 'projectile-mode-hook 'projectile-rails-on), and getting stuck

when i commented out (add-hook 'projectile-mode-hook 'projectile-rails-on) --- it was able to finish compiling everything ,  and then I re-added the hook... all is well

**Comment by rmm5t** [comment]
Oh, I see. Thanks for the update.
